// Mock data para preview local do sistema
export const mockUser = {
    id: '1',
    org_id: 'org-1',
    name: 'João Silva',
    email: 'joao@email.com',
    role: 'Admin' as const,
    phone: null,
    avatar_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
}

export const mockOrganization = {
    id: 'org-1',
    name: 'Silva & Advogados',
    plan: 'PRO' as const,
    settings: {
        whatsapp_webhook_url: '',
    },
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
}

export const mockClients = [
    {
        id: 'client-1',
        org_id: 'org-1',
        type: 'PF' as const,
        name: 'João da Silva Santos',
        email: 'joao.silva@email.com',
        phone: '11987654321',
        cpf_cnpj: '12345678901',
        preferences: { email_notifications: true, whatsapp_notifications: true },
        notes: null,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
    },
    {
        id: 'client-2',
        org_id: 'org-1',
        type: 'PF' as const,
        name: 'Maria Oliveira Costa',
        email: 'maria.oliveira@email.com',
        phone: '11987654322',
        cpf_cnpj: '98765432109',
        preferences: { email_notifications: true, whatsapp_notifications: false },
        notes: null,
        created_at: '2024-01-02T00:00:00Z',
        updated_at: '2024-01-02T00:00:00Z',
    },
    {
        id: 'client-3',
        org_id: 'org-1',
        type: 'PJ' as const,
        name: 'Tech Solutions LTDA',
        email: 'contato@techsolutions.com',
        phone: '1133334444',
        cpf_cnpj: '12345678000199',
        preferences: { email_notifications: true, whatsapp_notifications: true },
        notes: null,
        created_at: '2024-01-03T00:00:00Z',
        updated_at: '2024-01-03T00:00:00Z',
    },
]

export const mockMatters = [
    {
        id: 'matter-1',
        org_id: 'org-1',
        cnj: '00001234520248260100',
        tribunal: 'TJSP',
        uf: 'SP',
        parties_text: 'João da Silva Santos x Empresa XYZ',
        client_id: 'client-1',
        responsible_user_id: '1',
        status: 'Ativo' as const,
        advanced_fields: {},
        created_at: '2024-01-15T00:00:00Z',
        updated_at: '2024-01-15T00:00:00Z',
        client: mockClients[0],
        responsible_user: { ...mockUser, role: 'Admin' as const },
    },
    {
        id: 'matter-2',
        org_id: 'org-1',
        cnj: '00005678920248260200',
        tribunal: 'TJSP',
        uf: 'SP',
        parties_text: 'Maria Oliveira Costa x Condomínio ABC',
        client_id: 'client-2',
        responsible_user_id: '1',
        status: 'Ativo' as const,
        advanced_fields: {},
        created_at: '2024-01-20T00:00:00Z',
        updated_at: '2024-01-20T00:00:00Z',
        client: mockClients[1],
        responsible_user: { ...mockUser, role: 'Admin' as const },
    },
    {
        id: 'matter-3',
        org_id: 'org-1',
        cnj: '00009876520248260300',
        tribunal: 'TJSP',
        uf: 'SP',
        parties_text: 'Tech Solutions LTDA x Fornecedor DEF',
        client_id: 'client-3',
        responsible_user_id: '1',
        status: 'Ativo' as const,
        advanced_fields: {},
        created_at: '2024-02-01T00:00:00Z',
        updated_at: '2024-02-01T00:00:00Z',
        client: mockClients[2],
        responsible_user: { ...mockUser, role: 'Admin' as const },
    },
]

export const mockInboxItems = [
    {
        id: 'inbox-1',
        org_id: 'org-1',
        type: 'Intimacao' as const,
        status: 'Novo' as const,
        received_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        title: 'Intimação para apresentar contestação',
        body_text: 'Fica(m) Vossa(s) Senhoria(s) intimado(a)(s) a apresentar contestação no prazo legal. Processo: 0000123-45.2024.8.26.0100',
        matter_id: ' matter-1',
        client_id: 'client-1',
        responsible_user_id: null,
        metadata: {},
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        matter: mockMatters[0],
        client: mockClients[0],
        responsible_user: null,
    },
    {
        id: 'inbox-2',
        org_id: 'org-1',
        type: 'Publicacao' as const,
        status: 'Em triagem' as const,
        received_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        title: 'Publicação de sentença',
        body_text: 'Sentença proferida nos autos. Processo: 0000567-89.2024.8.26.0200',
        matter_id: 'matter-2',
        client_id: 'client-2',
        responsible_user_id: '1',
        metadata: {},
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        matter: mockMatters[1],
        client: mockClients[1],
        responsible_user: { ...mockUser, role: 'Admin' as const },
    },
    {
        id: 'inbox-3',
        org_id: 'org-1',
        type: 'Andamento' as const,
        status: 'Virou prazo' as const,
        received_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        title: 'Juntada de documentos',
        body_text: 'Documentos juntados aos autos. Processo: 0000987-65.2024.8.26.0300',
        matter_id: 'matter-3',
        client_id: 'client-3',
        responsible_user_id: '1',
        metadata: {},
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        matter: mockMatters[2],
        client: mockClients[2],
        responsible_user: { ...mockUser, role: 'Admin' as const },
    },
    {
        id: 'inbox-4',
        org_id: 'org-1',
        type: 'Intimacao' as const,
        status: 'Novo' as const,
        received_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        title: 'Intimação para especificar provas',
        body_text: 'Intimado(a) a especificar provas no prazo de 10 dias. Processo: 0000123-45.2024.8.26.0100',
        matter_id: 'matter-1',
        client_id: 'client-1',
        responsible_user_id: null,
        metadata: {},
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        matter: mockMatters[0],
        client: mockClients[0],
        responsible_user: null,
    },
]

export const mockDeadlines = [
    {
        id: 'deadline-1',
        org_id: 'org-1',
        title: 'Agravo de Instrumento',
        due_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Urgente',
        status: 'Agendado',
        tipo_prazo: 'DECISÃO - JUSTIÇA COMUM',
        providencia: 'AGRAVO DE INSTRUMENTO',
        responsavel: 'João Silva',
        autor: 'Sem Informação',
        reu: 'Sem Informação',
        matter_id: 'matter-1',
        responsible_user_id: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        matter: mockMatters[0],
    },
    {
        id: 'deadline-2',
        org_id: 'org-1',
        title: 'Manifestas sobre Despacho',
        due_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Alta',
        status: 'Atrasado',
        tipo_prazo: 'DESPACHO - JUSTIÇA COMUM',
        providencia: 'MANIFESTAS SOBRE DESPACHO',
        responsavel: 'João Silva',
        autor: 'Sem Informação',
        reu: 'Sem Informação',
        matter_id: 'matter-2',
        responsible_user_id: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        matter: mockMatters[1],
    },
    {
        id: 'deadline-3',
        org_id: 'org-1',
        title: 'Apelação',
        due_at: new Date(Date.now()).toISOString(),
        priority: 'Média',
        status: 'Agendado',
        tipo_prazo: 'DECISÃO - JUSTIÇA COMUM',
        providencia: 'APELACAO',
        responsavel: 'João Silva',
        autor: 'Sem Informação',
        reu: 'Sem Informação',
        matter_id: 'matter-1',
        responsible_user_id: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        matter: mockMatters[0],
    },
    {
        id: 'deadline-4',
        org_id: 'org-1',
        title: 'Recurso em Sentido Estrito',
        due_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Baixa',
        status: 'Agendado',
        tipo_prazo: 'DESPACHO - JUSTIÇA COMUM',
        providencia: 'RECURSO EM SENTIDO ESTRITO',
        responsavel: 'João Silva',
        autor: 'MATHEUS SOUSA D.',
        reu: 'VANESSA SARMENT..',
        matter_id: 'matter-2',
        responsible_user_id: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        matter: mockMatters[1],
    },
    {
        id: 'deadline-5',
        org_id: 'org-1',
        title: 'Manifestas em Provas',
        due_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Média',
        status: 'Cumprido',
        tipo_prazo: 'DECISÃO - JUSTIÇA COMUM',
        providencia: 'MANIFESTAS EM PROVAS',
        responsavel: 'João Silva',
        autor: 'Sem Informação',
        reu: 'Sem Informação',
        matter_id: 'matter-3',
        responsible_user_id: '1',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        matter: mockMatters[2],
    },
]

export const mockStats = {
    inbox: {
        total: mockInboxItems.filter(i => (i.status as string) !== 'Arquivado').length,
        novo: mockInboxItems.filter(i => (i.status as string) === 'Novo').length,
        em_triagem: mockInboxItems.filter(i => (i.status as string) === 'Em triagem').length,
        virou_prazo: mockInboxItems.filter(i => (i.status as string) === 'Virou prazo').length,
    },
    deadlines: {
        total: mockDeadlines.filter(d => ['Agendado', 'Atrasado'].includes(d.status as string)).length,
        aberto: mockDeadlines.filter(d => (d.status as string) === 'Agendado').length,
        atrasado: mockDeadlines.filter(d => (d.status as string) === 'Atrasado').length,
        hoje: mockDeadlines.filter(d => {
            const today = new Date().toDateString()
            return new Date(d.due_at).toDateString() === today && ['Agendado', 'Atrasado'].includes(d.status as string)
        }).length,
        proximos_3_dias: mockDeadlines.filter(d => {
            const due = new Date(d.due_at)
            const now = new Date()
            const diff = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
            return diff >= 0 && diff <= 3 && ['Agendado', 'Atrasado'].includes(d.status as string)
        }).length,
        proximos_7_dias: mockDeadlines.filter(d => {
            const due = new Date(d.due_at)
            const now = new Date()
            const diff = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)
            return diff >= 0 && diff <= 7 && ['Agendado', 'Atrasado'].includes(d.status as string)
        }).length,
    },
}
